var MW={},mw=MW;MW.version="0.0.1";MW.create=function(a){function b(){}b.prototype=a;return new b};(function(){"undefined"!==typeof module&&module.exports?module.exports=MW:(MW.m22=function(){return new MW.Matrix22},MW.m33=function(){return new MW.Matrix33},MW.m44=function(){return new MW.Matrix44},MW.v2=function(){return new MW.Vector2},MW.v3=function(){return new MW.Vector3},MW.v4=function(){return new MW.Vector4},MW.q=function(){return new MW.Quaternion})})();MW.Matrix22=function(){this.cols=this.rows=2;this.m=Array(4)};
MW.Matrix22.prototype={constructor:MW.Matrix22,identity:function(){this.m[0]=1;this.m[1]=0;this.m[2]=0;this.m[3]=1;return this},zero:function(){for(var a=0;a<this.m.length;++a)this.m[a]=0;return this},determinant:function(){return this.m[0]*this.m[3]-this.m[1]*this.m[2]},trace:function(){return this.m[0]+this.m[3]},copy:function(a){for(var b=0;b<this.m.length;++b)this.m[b]=a.m[b];return this},transpose:function(){for(var a=0;a<this.rows;++a)for(var b=a;b<this.cols;++b){var c=this.m[b*this.rows+a];
this.m[b*this.rows+a]=this.m[a*this.cols+b];this.m[a*this.cols+b]=c}return this},inverse:function(){var a=new MW.Matrix22,b=1/this.determinant();a.m[0]=b*this.m[3];a.m[1]=-b*this.m[1];a.m[2]=-b*this.m[2];a.m[3]=b*this.m[0];this.copy(a);return this},equal:function(a){for(var b=this.m.length-1;0<=b;--b)if(a.m[b]!==this.m[b])return!1;return!0},scalarMultiply:function(a){for(var b=this.m.length-1;0<=b;--b)this.m[b]*=a;return this},vectorMultiply:function(a){for(var b=[],c=0;c<this.rows;++c)b[c]=this.m[c*
this.columns+0]*a.x+this.m[c*this.columns+1]*a.y;a=new MW.Vector2;a.arraySet(b);return a},multiply:function(a){for(var b=new MW.Matrix22,c=0;c<this.rows;++c)for(var d=0;d<this.cols;++d)b.m[c*this.cols+d]=this.m[c*this.cols+0]*a.m[0*this.rows+d]+this.m[c*this.cols+1]*a.m[1*this.rows+d];this.copy(b);return this},add:function(a){for(var b=0;b<this.m.length;++b)this.m[b]+=a.m[b];return this},makeScale:function(a,b){this.zero();this.m[0]=a;this.m[3]=b;return this},makeRotation:function(a){var b=Math.cos(a),
a=Math.sin(a);this.m[0]=b;this.m[1]=-a;this.m[2]=a;this.m[3]=b;return this},getColumn:function(a){for(var b=[],c=0;c<this.rows;++c)b[c]=this.m[c*this.cols+a];a=new MW.Vector2;a.arraySet(b);return a},setColumn:function(a,b){this.m[0*this.cols+a]=b.x;this.m[1*this.cols+a]=b.y;return this},toString:function(){var a;a="Matrix:\n"+(""+this.m[0]+" "+this.m[1]+"\n");return a+=""+this.m[2]+" "+this.m[3]+"\n"}};MW.Matrix33=function(){this.columns=this.rows=3;this.m=Array(9)};
MW.Matrix33.prototype={constructor:MW.Matrix33,zero:function(){for(var a=this.m.length,b=0;b<a;++b)this.m[b]=0},identity:function(){this.zero();this.m[0]=1;this.m[4]=1;this.m[8]=1;return this},makeScale:function(a,b,c){this.zero();this.m[0]=a;this.m[4]=b;this.m[8]=c;return this},makeRotationX:function(a){var b=Math.cos(a),a=Math.sin(a);this.zero();this.m[0]=1;this.m[4]=b;this.m[5]=-a;this.m[7]=a;this.m[8]=b;return this},makeRotationY:function(a){var b=Math.cos(a),a=Math.sin(a);this.zero();this.m[0]=
b;this.m[2]=a;this.m[4]=1;this.m[6]=-a;this.m[8]=b;return this},makeRotationZ:function(a){var b=Math.cos(a),a=Math.sin(a);this.zero();this.m[0]=b;this.m[1]=-a;this.m[3]=a;this.m[4]=b;this.m[8]=1;return this},trace:function(){return this.m[0]+this.m[4]+this.m[8]},determinant:function(){return this.m[0]*(this.m[4]*this.m[8]-this.m[5]*this.m[7])-this.m[1]*(this.m[3]*this.m[8]-this.m[5]*this.m[6])+this.m[2]*(this.m[3]*this.m[7]-this.m[4]*this.m[6])},getColumn:function(a){for(var b=[],c=0;c<this.rows;++c)b[c]=
this.m[c*this.columns+a];a=new MW.Vector3;a.fromArray(b);return a},setColumn:function(a,b){this.m[0*this.columns+a]=b.x;this.m[1*this.columns+a]=b.y;this.m[2*this.columns+a]=b.z;return this},fromEulerAnglesXYZ:function(a,b,c){this.makeRotationX(a);a=new MW.Matrix33;a.makeRotationY(b);this.multiply(a);a.makeRotationZ(c);this.multiply(a);return this},fromAngleAxis:function(a,b){var c=Math.cos(a),d=Math.sin(a),e=1-c,f=b.y*b.y,l=b.z*b.z,g=b.x*b.y*e,h=b.x*b.z*e,i=b.y*b.z*e,j=b.x*d,k=b.y*d,d=b.z*d;this.m[0]=
c+b.x*b.x*e;this.m[1]=g-d;this.m[2]=h+k;this.m[3]=g+d;this.m[4]=c+f*e;this.m[5]=i-j;this.m[6]=h-k;this.m[7]=i+j;this.m[8]=c+l*e;return this},toAngleAxis:function(){var a=0.5*(this.trace()-1),a=Math.acos(a),b=new MW.Vector3;if(0<a)if(a<Math.PI)b.x=this.m[7]-this.m[5],b.y=this.m[2]-this.m[6],b.z=this.m[3]-this.m[1],b.normalize();else{var c;this.m[0]>=this.m[4]?this.m[0]>=this.m[8]?(b.x=0.5*Math.sqrt(this.m[0]-this.m[4]-this.m[8]+1),c=0.5/b.x,b.y=c*this.m[1],b.z=c*this.m[2]):(b.z=0.5*Math.sqrt(this.m[8]-
this.m[0]-this.m[4]+1),c=0.5/b.z,b.x=c*this.m[2],b.y=c*this.m[5]):this.m[4]>=this.m[8]?(b.y=0.5*Math.sqrt(this.m[4]-this.m[0]-this.m[8]+1),c=0.5/b.y,b.x=c*this.m[1],b.z=c*this.m[5]):(b.z=0.5*Math.sqrt(this.m[8]-this.m[0]-this.m[4]+1),c=0.5/b.z,b.x=c*this.m[2],b.y=c*this.m[5])}else b.x=1,b.y=0,b.z=0;return{angle:a,axis:b}},equal:function(a){for(var b=this.m.length-1;0<=b;--b)if(a.m[b]!==this.m[b])return!1;return!0},inverse:function(){var a=new MW.Matrix33;a.m[0]=this.m[4]*this.m[8]-this.m[5]*this.m[7];
a.m[1]=-(this.m[3]*this.m[8]-this.m[5]*this.m[6]);a.m[2]=this.m[3]*this.m[7]-this.m[4]*this.m[6];a.m[3]=-(this.m[1]*this.m[8]-this.m[2]*this.m[7]);a.m[4]=this.m[0]*this.m[8]-this.m[2]*this.m[6];a.m[5]=-(this.m[0]*this.m[7]-this.m[1]*this.m[6]);a.m[6]=this.m[1]*this.m[5]-this.m[2]*this.m[4];a.m[7]=-(this.m[0]*this.m[5]-this.m[2]*this.m[3]);a.m[8]=this.m[0]*this.m[4]-this.m[1]*this.m[3];a.transpose();var b=1/this.determinant();a.scalarMultiply(b);this.copy(a);return this},transpose:function(){for(var a=
0;a<this.rows;++a)for(var b=a;b<this.columns;++b){var c=this.m[b*this.rows+a];this.m[b*this.rows+a]=this.m[a*this.columns+b];this.m[a*this.columns+b]=c}return this},copy:function(a){for(var b=this.m.length-1;0<=b;--b)this.m[b]=a.m[b];return this},scalarMultiply:function(a){for(var b=this.m.length-1;0<=b;--b)this.m[b]*=a;return this},vectorMultiply:function(a){for(var b=[],c=0;c<this.rows;++c)b[c]=this.m[c*this.columns+0]*a.x+this.m[c*this.columns+1]*a.y+this.m[c*this.columns+2]*a.z;a=new MW.Vector3;
a.fromArray(b);return a},multiply:function(a){for(var b=new MW.Matrix33,c=0;c<this.rows;++c)for(var d=0;d<this.columns;++d)b.m[c*this.columns+d]=this.m[c*this.columns+0]*a.m[0*this.rows+d]+this.m[c*this.columns+1]*a.m[1*this.rows+d]+this.m[c*this.columns+2]*a.m[2*this.rows+d];this.copy(b);return this},toString:function(){var a;a="Matrix:\n"+(""+this.m[0]+" "+this.m[1]+" "+this.m[2]+"\n");a+=""+this.m[3]+" "+this.m[4]+" "+this.m[5]+"\n";return a+=""+this.m[6]+" "+this.m[7]+" "+this.m[8]+"\n"}};MW.Matrix44=function(){this.cols=this.rows=4;this.m=Array(16)};
MW.Matrix44.prototype={constructor:MW.Matrix44,zero:function(){for(var a=this.m.length,b=0;b<a;++b)this.m[b]=0;return this},identity:function(){this.zero();this.m[0]=1;this.m[5]=1;this.m[10]=1;this.m[15]=1;return this},setMatrix33:function(a){this.m[0]=a.m[0];this.m[1]=a.m[1];this.m[2]=a.m[2];this.m[4]=a.m[3];this.m[5]=a.m[4];this.m[6]=a.m[5];this.m[8]=a.m[6];this.m[9]=a.m[7];this.m[10]=a.m[8];return this},getMatrix33:function(){var a=MW.m33();a.m[0]=this.m[0];a.m[1]=this.m[1];a.m[2]=this.m[2];a.m[3]=
this.m[4];a.m[4]=this.m[5];a.m[5]=this.m[6];a.m[6]=this.m[8];a.m[7]=this.m[9];a.m[8]=this.m[10];return a},makeScale:function(a,b,c){this.identity();this.m[0]=a;this.m[5]=b;this.m[10]=c;return this},makeRotationX:function(a){a=MW.m33().makeRotationX(a);this.identity().setMatrix33(a);return this},makeRotationY:function(a){a=MW.m33().makeRotationY(a);this.identity().setMatrix33(a);return this},makeRotationZ:function(a){a=MW.m33().makeRotationZ(a);this.identity().setMatrix33(a);return this},trace:function(){return this.m[0]+
this.m[5]+this.m[10]+this.m[15]},minor:function(a,b){for(var c=new MW.Matrix33,d=0,e=0;e<this.rows;++e)for(var f=0;f<this.cols;++f)e!=a&&f!=b&&(c.m[d]=this.m[e*this.cols+f],++d);return c.determinant()},determinant:function(){var a=this.minor(0,0),b=-this.minor(0,1),c=this.minor(0,2),d=-this.minor(0,3);return this.m[0]*a+this.m[1]*b+this.m[2]*c+this.m[3]*d},getColumn:function(a){for(var b=[],c=0;c<this.rows;++c)b[c]=this.m[c*this.columns+a];a=new MW.Vector4;a.fromArray(b);return a},setColumn:function(a,
b){this.m[0*this.columns+a]=b.x;this.m[1*this.columns+a]=b.y;this.m[2*this.columns+a]=b.z;this.m[3*this.columns+a]=b.w},fromEulerAnglesXYZ:function(a,b,c){a=MW.m33().fromEulerAnglesXYZ(a,b,c);this.identity();this.setMatrix33(a);return this},fromAngleAxis:function(a,b){var c=MW.m33().fromAngleAxis(a,b);this.identity();this.setMatrix33(c);return this},toAngleAxis:function(){return this.getMatrix33().toAngleAxis()},equal:function(a){for(var b=this.m.length-1;0<=b;--b)if(a.m[b]!==this.m[b])return!1;return!0},
adjugate:function(){for(var a=new MW.Matrix44,b=0,c=0;c<this.rows;++c)for(var d=0;d<this.cols;++d){var e=(c+d)%2?-1:1;a.m[b]=this.minor(c,d)*e;++b}a.transpose();return a},inverse:function(){var a=1/this.determinant(),b=this.adjugate();b.scalarMultiply(a);this.copy(b);return this},transpose:function(){for(var a=0;a<this.rows;++a)for(var b=a;b<this.cols;++b){var c=this.m[b*this.rows+a];this.m[b*this.rows+a]=this.m[a*this.cols+b];this.m[a*this.cols+b]=c}},copy:function(a){for(var b=this.m.length-1;0<=
b;--b)this.m[b]=a.m[b]},scalarMultiply:function(a){for(var b=this.m.length-1;0<=b;--b)this.m[b]*=a},vectorMultiply:function(a){for(var b=[],c=0;c<this.rows;++c)b[c]=this.m[c*this.cols+0]*a.x+this.m[c*this.cols+1]*a.y+this.m[c*this.cols+2]*a.z+this.m[c*this.cols+3]*a.w;a=new MW.Vector4;a.fromArray(b);return a},multiply:function(a){for(var b=new MW.Matrix44,c=0;c<this.rows;++c)for(var d=0;d<this.cols;++d)b.m[c*this.cols+d]=this.m[c*this.cols+0]*a.m[0*this.rows+d]+this.m[c*this.cols+1]*a.m[1*this.rows+
d]+this.m[c*this.cols+2]*a.m[2*this.rows+d]+this.m[c*this.cols+3]*a.m[3*this.rows+d];this.copy(b)},toString:function(){var a;a="Matrix:\n"+(""+this.m[0]+" "+this.m[1]+" "+this.m[2]+" "+this.m[3]+"\n");a+=""+this.m[4]+" "+this.m[5]+" "+this.m[6]+" "+this.m[7]+"\n";a+=""+this.m[8]+" "+this.m[9]+" "+this.m[10]+" "+this.m[11]+"\n";return a+=""+this.m[12]+" "+this.m[13]+" "+this.m[14]+" "+this.m[15]+"\n"}};MW.Quaternion=function(){this.w=1;this.z=this.y=this.x=0};
MW.Quaternion.prototype={constructor:MW.Quaternion,set:function(a,b,c,d){this.w=a;this.x=b;this.y=c;this.z=d},fromAngleAxis:function(a,b){var c=0.5*a,d=Math.sin(c);this.w=Math.cos(c);this.x=b.x*d;this.y=b.y*d;this.z=b.z*d},toAngleAxis:function(){var a={};a.angle=2*Math.acos(this.w);var b=Math.sqrt(1-this.w*this.w);0<b?(b=1/b,a.axis=new MW.Vector3(this.x*b,this.y*b,this.z*b)):a.axis=new MW.Vector3(this.x,this.y,this.z);return a},toString:function(){return"Quaternion W:"+this.w+" X:"+this.x+" Y:"+this.y+
" Z:"+this.z}};var vec2=function(a,b){this.x=a;this.y=b},createVec2=function(a,b){return new vec2(a,b)};MW.Vector2=vec2;MW.v2=createVec2;
vec2.prototype={constructor:vec2,getSquaredLength:function(){return this.x*this.x+this.y*this.y},getLength:function(){return Math.sqrt(this.getSquaredLength())},getNormalized:function(){var a=new MW.Vector2;a.normalize();return a},getArray:function(){return[this.x,this.y]},zero:function(){this.y=this.x=0},normalize:function(){var a=1/this.getLength();this.x*=a;this.y*=a},arraySet:function(a){this.x=a[0];this.y=a[1]},set:function(a,b){this.x=a;this.y=void 0===b?a:b},equal:function(a){return 1.0E-5<
Math.abs(this.x-a.x)||1.0E-5<Math.abs(this.y-a.y)?!1:!0},toString:function(){return"Vector2  X:"+this.x+" Y:"+this.y}};MW.Vector3=function(a,b,c){this.x=a;this.y=b;this.z=c};
MW.Vector3.prototype={constructor:MW.Vector3,squaredLength:function(){return this.x*this.x+this.y*this.y+this.z*this.z},length:function(){return Math.sqrt(this.squaredLength())},normalize:function(){var a=1/this.length();this.x*=a;this.y*=a;this.z*=a},zero:function(){this.z=this.y=this.x=0},set:function(a,b,c){this.x=a;this.y=void 0===b?a:b;this.z=void 0===c?a:c},toArray:function(){return[this.x,this.y,this.z]},fromArray:function(a){this.x=a[0];this.y=a[1];this.z=a[2]},equal:function(a){return 1.0E-5<
Math.abs(this.x-a.x)||1.0E-5<Math.abs(this.y-a.y)||1.0E-5<Math.abs(this.z-a.z)?!1:!0},toString:function(){return"Vector3  X:"+this.x+" Y:"+this.y+" Z:"+this.z}};MW.Vector4=function(a,b,c,d){this.x=a;this.y=b;this.z=c;this.w=d};
MW.Vector4.prototype={constructor:MW.Vector4,getSquaredLength:function(){return this.x*this.x+this.y*this.y+this.z*this.z+this.w*this.w},getLength:function(){return Math.sqrt(this.getSquaredLength())},getNormalized:function(){var a=new MW.Vector4;a.normalize();return a},zero:function(){this.w=this.z=this.y=this.x=0;return this},normalize:function(){var a=1/this.getLength();this.x*=a;this.y*=a;this.z*=a;this.w*=a},fromArray:function(a){this.x=a[0];this.y=a[1];this.z=a[2];this.w=a[3]},toArray:function(){return[this.x,
this.y,this.z,this.w]},set:function(a,b,c,d){this.x=a;this.y=void 0===b?a:b;this.z=void 0===c?a:c;this.w=void 0===d?a:d},equal:function(a){return 1.0E-5<Math.abs(this.x-a.x)||1.0E-5<Math.abs(this.y-a.y)||1.0E-5<Math.abs(this.z-a.z)||1.0E-5<Math.abs(this.w-a.w)?!1:!0},toString:function(){return"Vector4  X:"+this.x+" Y:"+this.y+" Z:"+this.z+" W:"+this.w}};
